# Use a base image with ffmpeg pre-installed
FROM jrottenberg/ffmpeg:4.3-ubuntu

# Install Node.js
RUN apt-get update && apt-get install -y nodejs npm

# Set up the work directory for your application
WORKDIR /ffmpeg-server

# Copy application files
COPY . .

# Install dependencies
RUN npm install

# Expose the server port
EXPOSE 80

# Start the application
CMD ["node", "src/app.js"]
